name: Build Executable

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install pkg
              run: npm install -g pkg

            - name: Build Executable
              run: pkg index.js --targets node18-win-x64

            - name: Upload Executable
              uses: actions/upload-artifact@v2
              with:
                  name: executables
                  path: index-win.exe